// Mocks generated by Mockito 5.0.5 from annotations
// in rx_widget_demo/test/homepage_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/src/client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rx_widget_demo/service/weather_entry.dart' as _i5;
import 'package:rx_widget_demo/service/weather_service.dart' as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeClient extends _i1.Fake implements _i2.Client {}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i3.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient()) as _i2.Client);
  @override
  _i4.Future<List<_i5.WeatherEntry>> getWeatherEntriesForCity(String? filter) =>
      (super.noSuchMethod(
              Invocation.method(#getWeatherEntriesForCity, [filter]),
              returnValue:
                  Future<List<_i5.WeatherEntry>>.value(<_i5.WeatherEntry>[]))
          as _i4.Future<List<_i5.WeatherEntry>>);
}
